// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Smart_Gadget

#include "../ui.h"

void ui_Weather_screen_init(void)
{
    ui_Weather = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Weather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Weather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Weather, &ui_img_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Weather, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Icons = lv_obj_create(ui_Weather);
    lv_obj_set_height(ui_Weather_Icons, 206);
    lv_obj_set_width(ui_Weather_Icons, lv_pct(100));
    lv_obj_set_x(ui_Weather_Icons, 0);
    lv_obj_set_y(ui_Weather_Icons, -2);
    lv_obj_set_align(ui_Weather_Icons, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Weather_Icons, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Weather_Icons, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Weather_Icons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shiduIcon = lv_label_create(ui_Weather_Icons);
    lv_obj_set_width(ui_shiduIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shiduIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shiduIcon, 22);
    lv_obj_set_y(ui_shiduIcon, 0);
    lv_obj_set_align(ui_shiduIcon, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_shiduIcon, "");
    lv_obj_set_style_text_color(ui_shiduIcon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shiduIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shiduIcon, &ui_font_uavfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PM25Icon = lv_label_create(ui_Weather_Icons);
    lv_obj_set_width(ui_PM25Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PM25Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PM25Icon, 49);
    lv_obj_set_y(ui_PM25Icon, -78);
    lv_obj_set_align(ui_PM25Icon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PM25Icon, "");
    lv_obj_set_style_text_color(ui_PM25Icon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PM25Icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PM25Icon, &ui_font_uavfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fengsuIcon = lv_label_create(ui_Weather_Icons);
    lv_obj_set_width(ui_fengsuIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fengsuIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fengsuIcon, -22);
    lv_obj_set_y(ui_fengsuIcon, 0);
    lv_obj_set_align(ui_fengsuIcon, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_fengsuIcon, "");
    lv_obj_set_style_text_color(ui_fengsuIcon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fengsuIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fengsuIcon, &ui_font_uavfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_qiyaLabel = lv_label_create(ui_Weather_Icons);
    lv_obj_set_width(ui_qiyaLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_qiyaLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_qiyaLabel, -22);
    lv_obj_set_y(ui_qiyaLabel, 0);
    lv_obj_set_align(ui_qiyaLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_qiyaLabel, "--hPa");
    lv_obj_set_style_text_color(ui_qiyaLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_qiyaLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fengxiangLabel = lv_label_create(ui_Weather_Icons);
    lv_obj_set_width(ui_fengxiangLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fengxiangLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fengxiangLabel, -1);
    lv_obj_set_y(ui_fengxiangLabel, 0);
    lv_obj_set_align(ui_fengxiangLabel, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_fengxiangLabel, "--du");
    lv_obj_set_style_text_color(ui_fengxiangLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fengxiangLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PM25Label = lv_label_create(ui_Weather_Icons);
    lv_obj_set_width(ui_PM25Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PM25Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PM25Label, 157);
    lv_obj_set_y(ui_PM25Label, -138);
    lv_obj_set_align(ui_PM25Label, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_PM25Label, "--ug/m^3");
    lv_obj_set_style_text_color(ui_PM25Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PM25Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shiduArc = lv_arc_create(ui_Weather_Icons);
    lv_obj_set_width(ui_shiduArc, 60);
    lv_obj_set_height(ui_shiduArc, 60);
    lv_obj_set_x(ui_shiduArc, 10);
    lv_obj_set_y(ui_shiduArc, 1);
    lv_obj_set_align(ui_shiduArc, LV_ALIGN_LEFT_MID);
    lv_arc_set_range(ui_shiduArc, 0, 100);
    lv_obj_set_style_arc_color(ui_shiduArc, lv_color_hex(0x0F0F27), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_shiduArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_shiduArc, lv_color_hex(0xD80C0C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_shiduArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_shiduArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_shiduArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_tempArc = lv_arc_create(ui_Weather_Icons);
    lv_obj_set_width(ui_tempArc, 60);
    lv_obj_set_height(ui_tempArc, 60);
    lv_obj_set_x(ui_tempArc, 0);
    lv_obj_set_y(ui_tempArc, 1);
    lv_obj_set_align(ui_tempArc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_tempArc, -10, 100);
    lv_obj_set_style_arc_color(ui_tempArc, lv_color_hex(0x0F0F27), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_tempArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_tempArc, lv_color_hex(0xD80C0C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_tempArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_tempArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_fengsuArc = lv_arc_create(ui_Weather_Icons);
    lv_obj_set_width(ui_fengsuArc, 60);
    lv_obj_set_height(ui_fengsuArc, 60);
    lv_obj_set_x(ui_fengsuArc, -10);
    lv_obj_set_y(ui_fengsuArc, 1);
    lv_obj_set_align(ui_fengsuArc, LV_ALIGN_RIGHT_MID);
    lv_arc_set_range(ui_fengsuArc, 0, 2000);
    lv_obj_set_style_arc_color(ui_fengsuArc, lv_color_hex(0x0F0F27), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_fengsuArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_fengsuArc, lv_color_hex(0xD80C0C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_fengsuArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_fengsuArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fengsuArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_PM25Arc = lv_arc_create(ui_Weather_Icons);
    lv_obj_set_width(ui_PM25Arc, 60);
    lv_obj_set_height(ui_PM25Arc, 60);
    lv_obj_set_x(ui_PM25Arc, 48);
    lv_obj_set_y(ui_PM25Arc, -73);
    lv_obj_set_align(ui_PM25Arc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_PM25Arc, 0, 2500);
    lv_obj_set_style_arc_color(ui_PM25Arc, lv_color_hex(0x0F0F27), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_PM25Arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_PM25Arc, lv_color_hex(0xD80C0C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_PM25Arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PM25Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PM25Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_qiyaIcon = lv_label_create(ui_Weather_Icons);
    lv_obj_set_width(ui_qiyaIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_qiyaIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_qiyaIcon, -23);
    lv_obj_set_y(ui_qiyaIcon, 65);
    lv_obj_set_align(ui_qiyaIcon, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_qiyaIcon, "");
    lv_obj_set_style_text_color(ui_qiyaIcon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_qiyaIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_qiyaIcon, &ui_font_uavfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempIcon = lv_label_create(ui_Weather_Icons);
    lv_obj_set_width(ui_tempIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempIcon, 0);
    lv_obj_set_y(ui_tempIcon, 1);
    lv_obj_set_align(ui_tempIcon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempIcon, "");
    lv_obj_set_style_text_color(ui_tempIcon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempIcon, &ui_font_uavfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fengxiangIcon = lv_label_create(ui_Weather_Icons);
    lv_obj_set_width(ui_fengxiangIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fengxiangIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fengxiangIcon, 0);
    lv_obj_set_y(ui_fengxiangIcon, 65);
    lv_obj_set_align(ui_fengxiangIcon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fengxiangIcon, "");
    lv_obj_set_style_text_color(ui_fengxiangIcon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fengxiangIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fengxiangIcon, &ui_font_uavfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_heightIcon = lv_label_create(ui_Weather_Icons);
    lv_obj_set_width(ui_heightIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_heightIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_heightIcon, 22);
    lv_obj_set_y(ui_heightIcon, 65);
    lv_obj_set_align(ui_heightIcon, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_heightIcon, "");
    lv_obj_set_style_text_color(ui_heightIcon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_heightIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_heightIcon, &ui_font_uavfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_heightArc = lv_arc_create(ui_Weather_Icons);
    lv_obj_set_width(ui_heightArc, 60);
    lv_obj_set_height(ui_heightArc, 60);
    lv_obj_set_x(ui_heightArc, 12);
    lv_obj_set_y(ui_heightArc, 65);
    lv_obj_set_align(ui_heightArc, LV_ALIGN_LEFT_MID);
    lv_arc_set_range(ui_heightArc, -100, 255);
    lv_obj_set_style_arc_color(ui_heightArc, lv_color_hex(0x0F0F27), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_heightArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_heightArc, lv_color_hex(0xD80C0C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_heightArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_heightArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_heightArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_fengxiangArc = lv_arc_create(ui_Weather_Icons);
    lv_obj_set_width(ui_fengxiangArc, 60);
    lv_obj_set_height(ui_fengxiangArc, 60);
    lv_obj_set_x(ui_fengxiangArc, 0);
    lv_obj_set_y(ui_fengxiangArc, 65);
    lv_obj_set_align(ui_fengxiangArc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_fengxiangArc, 0, 360);
    lv_obj_set_style_arc_color(ui_fengxiangArc, lv_color_hex(0x0F0F27), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_fengxiangArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_fengxiangArc, lv_color_hex(0xD80C0C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_fengxiangArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_fengxiangArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fengxiangArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_qiyaArc = lv_arc_create(ui_Weather_Icons);
    lv_obj_set_width(ui_qiyaArc, 60);
    lv_obj_set_height(ui_qiyaArc, 60);
    lv_obj_set_x(ui_qiyaArc, -10);
    lv_obj_set_y(ui_qiyaArc, 65);
    lv_obj_set_align(ui_qiyaArc, LV_ALIGN_RIGHT_MID);
    lv_arc_set_range(ui_qiyaArc, 30, 110);
    lv_obj_set_style_arc_color(ui_qiyaArc, lv_color_hex(0x0F0F27), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_qiyaArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_qiyaArc, lv_color_hex(0xD80C0C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_qiyaArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_qiyaArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_qiyaArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_heightLabel = lv_label_create(ui_Weather_Icons);
    lv_obj_set_width(ui_heightLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_heightLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_heightLabel, -175);
    lv_obj_set_y(ui_heightLabel, 0);
    lv_obj_set_align(ui_heightLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_heightLabel, "--m");
    lv_obj_set_style_text_color(ui_heightLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_heightLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shiduLabel = lv_label_create(ui_Weather_Icons);
    lv_obj_set_width(ui_shiduLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shiduLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shiduLabel, -187);
    lv_obj_set_y(ui_shiduLabel, -67);
    lv_obj_set_align(ui_shiduLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_shiduLabel, "--%");
    lv_obj_set_style_text_color(ui_shiduLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shiduLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempLabel = lv_label_create(ui_Weather_Icons);
    lv_obj_set_width(ui_tempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempLabel, -106);
    lv_obj_set_y(ui_tempLabel, -67);
    lv_obj_set_align(ui_tempLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_tempLabel, "--C");
    lv_obj_set_style_text_color(ui_tempLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fengsuLabel = lv_label_create(ui_Weather_Icons);
    lv_obj_set_width(ui_fengsuLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fengsuLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fengsuLabel, -21);
    lv_obj_set_y(ui_fengsuLabel, -67);
    lv_obj_set_align(ui_fengsuLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_fengsuLabel, "--cm/s");
    lv_obj_set_style_text_color(ui_fengsuLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fengsuLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Weather);
    lv_obj_set_height(ui_Panel1, 29);
    lv_obj_set_width(ui_Panel1, lv_pct(100));
    lv_obj_set_align(ui_Panel1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x14191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 10);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label2, "");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_iconfont22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 60);
    lv_obj_set_y(ui_Label3, 2);
    lv_obj_set_align(ui_Label3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label3, "");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_iconfont22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Weather);
    lv_obj_set_width(ui_Panel3, 96);
    lv_obj_set_height(ui_Panel3, 62);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, 29);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xB3B3B3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label9, lv_pct(101));
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_label_set_long_mode(ui_Label9, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Label9, "ssid:");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label9, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifissid = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_wifissid, lv_pct(66));
    lv_obj_set_height(ui_wifissid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifissid, 18);
    lv_obj_set_y(ui_wifissid, 0);
    lv_label_set_long_mode(ui_wifissid, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_wifissid, "myssid");
    lv_obj_set_style_text_color(ui_wifissid, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifissid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_wifissid, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifissid, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label11, lv_pct(100));
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 0);
    lv_obj_set_y(ui_Label11, 12);
    lv_label_set_long_mode(ui_Label11, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Label11, "psw:");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_password = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_password, lv_pct(65));
    lv_obj_set_height(ui_password, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_password, 18);
    lv_obj_set_y(ui_password, 12);
    lv_label_set_long_mode(ui_password, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_password, "mypassword");
    lv_obj_set_style_text_color(ui_password, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_password, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_password, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_password, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label14, lv_pct(100));
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 0);
    lv_obj_set_y(ui_Label14, 24);
    lv_label_set_long_mode(ui_Label14, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Label14, "IP:");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label14, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ipadress = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_ipadress, lv_pct(80));
    lv_obj_set_height(ui_ipadress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ipadress, 12);
    lv_obj_set_y(ui_ipadress, 24);
    lv_label_set_long_mode(ui_ipadress, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_ipadress, "unknwon");
    lv_obj_set_style_text_color(ui_ipadress, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ipadress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ipadress, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ipadress, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_port, lv_pct(100));
    lv_obj_set_height(ui_port, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port, 0);
    lv_obj_set_y(ui_port, 36);
    lv_label_set_long_mode(ui_port, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_port, "Port:unknwon");
    lv_obj_set_style_text_color(ui_port, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_port, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label12, lv_pct(100));
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 0);
    lv_obj_set_y(ui_Label12, 48);
    lv_label_set_long_mode(ui_Label12, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Label12, "LIP:");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label12, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ipadress2 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_ipadress2, lv_pct(70));
    lv_obj_set_height(ui_ipadress2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ipadress2, 17);
    lv_obj_set_y(ui_ipadress2, 48);
    lv_label_set_long_mode(ui_ipadress2, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_ipadress2, "unknown");
    lv_obj_set_style_text_color(ui_ipadress2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ipadress2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ipadress2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ipadress2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_shiduArc, ui_event_shiduArc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tempArc, ui_event_tempArc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fengsuArc, ui_event_fengsuArc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PM25Arc, ui_event_PM25Arc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_heightArc, ui_event_heightArc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fengxiangArc, ui_event_fengxiangArc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_qiyaArc, ui_event_qiyaArc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Weather, ui_event_Weather, LV_EVENT_ALL, NULL);

}
